[package]
description = "Various macros to help with database queries and tables"
edition = "2021"
license = "MIT"
name = "db-helpers"
version = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = {version = "0.7"}
