[package]
name = "db-helpers"
version = "0.1.0"
edition = "2021"
license="MIT"
description = "Various macros to help with database queries and tables"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
