[package]
description = "Various macros to help with database queries and tables"
edition = "2021"
license = "MIT"
name = "db-helpers"
version = "0.11.1"
[workspace]
members = ["derive", "types"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = { version = "0.7", optional = true }
derive = { path = "./derive" }
types = { path = "./types" }

[features]
default = ["pg"]
pg = ["tokio-postgres"]
